//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.STORAGE
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity_Place_Pin
    {
        public entity_Place_Pin()
        {
            this.entity_Issues = new HashSet<entity_Issues>();
        }
    
        public string PIN { get; set; }
        public string Place_Name { get; set; }
        public string District { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<entity_Issues> entity_Issues { get; set; }
    }
}
