//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.STORAGE
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity_Issues
    {
        public entity_Issues()
        {
            this.entity_Attachments = new HashSet<entity_Attachments>();
            this.entity_Comments = new HashSet<entity_Comments>();
        }
    
        public string IssueId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IssueVisibility { get; set; }
        public Nullable<bool> CreatorVisibility { get; set; }
        public Nullable<byte> Category_ID { get; set; }
        public string CreatorID { get; set; }
        public string Comment_ID { get; set; }
        public System.DateTime Creation_date { get; set; }
        public string PIN { get; set; }
    
        public virtual ICollection<entity_Attachments> entity_Attachments { get; set; }
        public virtual ICollection<entity_Comments> entity_Comments { get; set; }
        public virtual entity_Place_Pin entity_Place_Pin { get; set; }
    }
}
