//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.STORAGE
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity_Attachments
    {
        public string Attachment_Id { get; set; }
        public string Filename { get; set; }
        public string IssueId { get; set; }
    
        public virtual entity_Issues entity_Issues { get; set; }
    }
}
