//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.STORAGE
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity_IssuesCountPerDays
    {
        public System.DateTime Date { get; set; }
        public long Count { get; set; }
    }
}
