//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V1.STORAGE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STORAGE_Con : DbContext
    {
        public STORAGE_Con()
            : base("name=STORAGE_Con")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<entity_Attachments> entity_Attachments { get; set; }
        public DbSet<entity_Comments> entity_Comments { get; set; }
        public DbSet<entity_Issues> entity_Issues { get; set; }
        public DbSet<entity_IssuesCountPerDays> entity_IssuesCountPerDays { get; set; }
        public DbSet<entity_Place_Pin> entity_Place_Pin { get; set; }
    }
}
